version: "3.7"

services:
  wordpress-www:
    image: wordpress:latest
    restart: always
    networks:
      - minha_rede
    volumes:
      - capacitaja_wordpress_data:/var/www/html
      - wordpress_php_data:/usr/local/etc/php
    environment:
      WORDPRESS_DB_NAME: capacitaja
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Admin!!Capacit@0408
      WP_REDIS_URI: redis://:nPcnRWOLitkZsvnUiUIrGm08BcljWa73@redis:6379
      WP_REDIS_OPT_LIMITER_MAX: 1
      WP_REDIS_OPT_LIMITER_DURATION: 3000
      WP_LOCALE: pt_BR
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true

        # HTTP (redireciona para HTTPS)
        - traefik.http.routers.wordpress.rule=Host(`capacitaja.com`) || Host(`www.capacitaja.com`)
        - traefik.http.routers.wordpress.entrypoints=web
        - traefik.http.routers.wordpress.middlewares=redirect-to-https@docker

        # HTTPS
        - traefik.http.routers.wordpress-secure.rule=Host(`capacitaja.com`) || Host(`www.capacitaja.com`)
        - traefik.http.routers.wordpress-secure.entrypoints=websecure
        - traefik.http.routers.wordpress-secure.tls.certresolver=letsencryptresolver


        # Serviço
        - traefik.http.services.wordpress.loadbalancer.server.port=80
        - traefik.http.services.wordpress.loadbalancer.passHostHeader=true

        # Middleware de redirecionamento
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

volumes:
  capacitaja_wordpress_data:
    external: true
  wordpress_php_data:
    external: true

networks:
  minha_rede:
    external: true
